### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by sirhopcount** [wercker/cronetes#6]
Hi,

I am trying to deploy cronetes on our K8S cluster but the application crashes on start:

```
INFO[0000] Starting server                              
DEBU[0000] Parsing config                               
DEBU[0000] Creating kube client                         
DEBU[0000] Creating cron scheduler                      
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x40215a]

goroutine 1 [running]:
panic(0x16f7a20, 0xc8200140a0)
        /usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/wercker/cronetes/vendor/gopkg.in/urfave/cli%2ev1.HandleAction.func1(0xc8204c7270)
        /go/src/github.com/wercker/cronetes/vendor/gopkg.in/urfave/cli.v1/app.go:472 +0x417
panic(0x16f7a20, 0xc8200140a0)
        /usr/local/go/src/runtime/panic.go:443 +0x4e9
main.cronAction(0xc8201dea00, 0x0, 0x0)
        /go/src/github.com/wercker/cronetes/cron.go:86 +0x102a
reflect.Value.call(0x140a5c0, 0x1c47de0, 0x13, 0x191f530, 0x4, 0xc8204c71d0, 0x1, 0x1, 0x0, 0x0, ...)
        /usr/local/go/src/reflect/value.go:435 +0x120d
reflect.Value.Call(0x140a5c0, 0x1c47de0, 0x13, 0xc8204c71d0, 0x1, 0x1, 0x0, 0x0, 0x0)
        /usr/local/go/src/reflect/value.go:303 +0xb1
github.com/wercker/cronetes/vendor/gopkg.in/urfave/cli%2ev1.HandleAction(0x140a5c0, 0x1c47de0, 0xc8201dea00, 0x0, 0x0)
        /go/src/github.com/wercker/cronetes/vendor/gopkg.in/urfave/cli.v1/app.go:481 +0x2ee
github.com/wercker/cronetes/vendor/gopkg.in/urfave/cli%2ev1.Command.Run(0x1923ad8, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1a0b6b0, 0x13, 0x0, ...)
        /go/src/github.com/wercker/cronetes/vendor/gopkg.in/urfave/cli.v1/command.go:186 +0x1301
github.com/wercker/cronetes/vendor/gopkg.in/urfave/cli%2ev1.(*App).Run(0xc8200f7500, 0xc82000a0a0, 0xa, 0xa, 0x0, 0x0)
        /go/src/github.com/wercker/cronetes/vendor/gopkg.in/urfave/cli.v1/app.go:235 +0xa9c
main.main()
        /go/src/github.com/wercker/cronetes/main.go:83 +0xb73
```

For testing purposes we started the application manually with the following option:

```
./cronetes --debug --kube-endpoint kubenetes --kube-ca-file /var/run/secrets/kubernetes.io/serviceaccount/ca.crt --kube-token $(cat /var/run/secrets/kubernetes.io/serviceaccount/token) cron --config=/cronetes-picacl.yaml
```
The config file (/cronetes-picacl.yaml) looks like this:

```
- schedule: 10 * * * * *
  apiVersion: batch/v1
  kind: Job
  metadata:
    name: pi
  spec:
    template:
      metadata:
        name: pi
      spec:
        containers:
        - name: pi
          image: perl
          command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
        restartPolicy: Never
```

Could this have something to do with how we implemented the Bearer token?

Because from what I understand from the K8S documentation the token is placed in _/var/run/secrets/kubernetes.io/serviceaccount/token_ so I was wondering why the kube-token option should contain the token itself and not the path to the token.

**Comment by hatchan** [comment]
First off, if you are using a more recent version of Kubernetes, consider using their native solution: https://kubernetes.io/docs/user-guide/cron-jobs/ It wasn't available at the time of the development of this tool.

The config that you provided contains a issue. It should be: 

```
- schedule: 10 * * * * *
  job:
    apiVersion: batch/v1
    kind: Job
    metadata:
      name: pi
    spec:
      template:
        metadata:
          name: pi
        spec:
          containers:
          - name: pi
            image: perl
            command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
          restartPolicy: Never
```

Also, looking at the stack trace it looks like it is a slightly older version, make sure you use the latest commit.
